name: SwiftUIExample
options:
  bundleIdPrefix: com.applemapssheet
  deploymentTarget:
    iOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  AppleMapsSheet:
    path: ../..

settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.0"

targets:
  SwiftUIExample:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: .
        includes:
          - "*.swift"
        excludes:
          - "project.yml"
      - path: Resources
        optional: true
    resources:
      - path: Resources/Assets.xcassets
        optional: true
    dependencies:
      - package: AppleMapsSheet
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.applemapssheet.swiftuiexample
        PRODUCT_NAME: SwiftUIExample
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_ENTITLEMENTS: ""
    info:
      path: Resources/Info.plist
      properties:
        CFBundleName: SwiftUIExample
        CFBundleDisplayName: SwiftUI Example
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
